"""add_shipping_address_to_orders

Revision ID: 05d179d28472
Revises: d2c9d9a3db41
Create Date: 2026-04-04 20:21:23.346900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d179d28472'
down_revision: Union[str, Sequence[str], None] = 'd2c9d9a3db41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'pincode')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'address_line2')
    op.drop_column('orders', 'address_line1')
    # ### end Alembic commands ###
